### ISSUE TITLE
Compatability with sci-kit learn 1.3.0

### ISSUE THREAD

**Issue by TomBurdge** [neocortexdb/functime#13]
Thank you for making what looks like an amazing module functime team!
The package currently requires sci-kit learn 1.2.2, is it possible to get it compatible with 1.3.0? 
I want to try out functime's performance in a repo for which I need sci-kit learn 1.3.0.

(Unnecessary extra info: This is for 1.3.0's hdbscan. I know I could just use the hdbscan module, but I expect the hdbscan module may become semi-redundant with hdbscan in sci-kit learn).

**Comment by topher-lo** [comment]
Haven't tested scikit-learn 1.3.0 yet. Will put it in the backlog as there are 2-3 high impact features to be released very soon 🚀 . Stay tuned @TomBurdge
