### ISSUE TITLE
Optimization: benford_correlation

### ISSUE THREAD

**Issue by abstractqqq** [neocortexdb/functime#41]
There are three ways to optimize the existing benford_correlation: 

1. relies on strings to extract the first digit of a number. But we don't need strings actually. We can get around strings mathematically.
2. Since corr is scale invariant, we do not need to compute counts.sum()
3. The "Benford distribution" is static. We should keep it as a global variable computed at module initialization instead of reapeatedly computing it at runtime.

A new implementation will be:
```

benford_dist_series = (1 + 1 / pl.int_range(1, 10, eager=True)).log10()
def benford_correlation2(x: pl.Expr) -> pl.Expr:
    
    counts = (
        (x.abs()/(pl.lit(10).pow(x.abs().log10().floor())))
        .drop_nans()
        .cast(pl.UInt8)
        .append(pl.int_range(1, 10, eager=False))
        .sort()
        .value_counts()
        .struct.field("counts") - pl.lit(1)
    )
    # no need to divide because correlation is invariant under scaling
    return pl.corr(counts, pl.lit(benford_dist_series))

```
To test, we can try this on the following df:
```
test_df = pl.DataFrame({
    "a": [float(i) + 0.1 for i in range(-100_000, 100_000)]
})
```

### **Only problem:** 
There seems to be a precision issue that only affects the value 1000. By my testing, for sequences without the 1000 in it, it is accurate. I can't guarantee 1000 is the only problematic value, however.
![image](https://github.com/neocortexdb/functime/assets/72534736/5a7dc9d6-609d-43c8-8ed0-ae5271eec984)

### **3x Less Time (tested on my local system)**
![Capture](https://github.com/neocortexdb/functime/assets/72534736/b0572234-3b96-4274-88a1-e46c21906ac2)

**Comment by MathieuCayssol** [comment]
1. I did it mathematically initially but @vienneraphael found out that is at least x2 faster using the string implementation.
2. Good point 
3. As it's very fast to compute I would agree. @topher-lo What do you think?

**Comment by abstractqqq** [comment]
@MathieuCayssol Do you or Raphael have time benchmarks for string impl vs. math impl? Thanks. Locally for me math impl is much faster.

**Comment by topher-lo** [comment]
@abstractqqq here is its: https://github.com/neocortexdb/functime/pull/26#issuecomment-1716273477

**Comment by MathieuCayssol** [comment]
@vienneraphael has the string vs math benchmarks

**Comment by vienneraphael** [comment]
@abstractqqq Here is mine: 

![image](https://github.com/neocortexdb/functime/assets/129849233/6ba2e9c7-38a0-452f-9547-49f2a6ef1dac)

**Comment by vienneraphael** [comment]
I computed times for various frames sizes:

| Length | Utf8 time | Math time | Runs
| --- | --- | --- | --- |
| 20k | 1.47 ms ± 39.4 $\mu s$ | 1.75 ms ± 14.8 $\mu s$ |  7000 |
| 200k | 8.72 ms ± 106 $\mu s$ | 9.62 ms  ± 36.6 $\mu s$ | 700 |
| 2M | 96.6 ms ± 1.58ms | 104 ms ± 1.3ms | 70 |
| 20M | 1.02s ± 85ms | 1.07s ± 12.1ms | 7 |
| 200M | 11.8s ± 628ms | 11.5s ± 276ms  | 7 | 

Both are nearly equal for me. Though Utf8 might be more resilient upon outliers. What do you think ?

**Comment by vienneraphael** [comment]
Here is the second benchmark with polars 0.19.2:

| Length | Utf8 time | Math time | Runs
| --- | --- | --- | --- |
| 20k | 1.48 ms ± 16.1 $\mu s$ | 1.59 ms ± 39.5 $\mu s$ |  7000 |
| 200k | 8.64 ms ± 193 $\mu s$ | 9.52 ms  ± 39.5 $\mu s$ | 700 |
| 2M | 96.9 ms ± 1.34ms | 107 ms ± 694 $\mu s$ | 70 |
| 20M | 980ms ± 29ms | 1.08s ± 14.1ms | 7 |
| 200M | 11.8s ± 1.18s| 11.3s ± 257ms  | 7 |

**Comment by topher-lo** [comment]
The numbers are so close. My vote is just to keep the existing solution. Revisit if any users comment. @abstractqqq does this work?

**Comment by abstractqqq** [comment]
This is very interesting. I think this might be either OS/hardware difference, which we cannot control.. I am in favor of having more stability (precision issue is nagging).  We will keep the str method as the default and the math method as secondary.
