### ISSUE TITLE
Binned Entropy Implementation is wrong

### ISSUE THREAD

**Issue by abstractqqq** [neocortexdb/functime#42]
Currently the binned_entropy is wrong because pl.Series's hist function's behavior differs wildly from NumPy's np.histogram. The generated bins are wildly different. I am not sure if this is a bug on Polar's side, or this is just how they intend people to use the hist function on Series. Personally, I don't think it is a Polars error, but rather a "quirk". Another detail which took me a while to notice is that NumPy's histogram seems to be left_closed, while default behavior of Polars's right_closed.

![image](https://github.com/neocortexdb/functime/assets/72534736/9b13b40c-b65a-423d-838b-b87e59f7a27c)

I compared the current result vs. tsfresh's result, which replies on NumPy's histogram function, we can see the result is wrong.

![image](https://github.com/neocortexdb/functime/assets/72534736/3f6e17e3-2d37-43b0-a0e3-d2e7e2c12843)

I made a rewrite, which works on pl.Exprs, which I think is more preferable for the future of the package.

```
def binned_entropy_rewrite(x:pl.Expr, bin_count: int = 10) -> pl.Expr:
    step_size = 1/bin_count
    breaks = np.linspace(step_size, stop = 1 - step_size, num = bin_count - 1)
    scaled_x = (x - x.min()) / (x.max() - x.min()) # This steps slows down the calculation
    # Left closed because we want to micmic NumPy's histogram's behavior
    return scaled_x.cut(breaks, left_closed=True).value_counts().struct.field("counts").entropy().suffix("_binned_entropy")
```

If we want to work lazily, we will not be able to set the break points before scanning through the data. However, if can map the values of x into [0,1] by using min-max scaling which preserves the distribution (bins) within the break point ranges. 

The only downside to this approach is that it seems to be much slower than NumPy (tsfresh) implementation as of now. On a Series/array of size 100_000, this took 3.7ms while tsfresh took 0.6ms. I currently don't see how to improve this further at this moment.

**Comment by topher-lo** [comment]
@abstractqqq let's go for your lazy / pl.Expr implementation. The time difference is marginal. The speed ups across other features should make up for the performance hit here.
