### ISSUE TITLE
Optimization: count_above_mean

### ISSUE THREAD

**Issue by abstractqqq** [neocortexdb/functime#43]
```
def count_above_mean(x: pl.Expr) -> pl.Expr:
    """Count the number of values that are above the mean.

    Parameters
    ----------
    x : pl.Expr | pl.Series
        Input time-series.

    Returns
    -------
    int
    """
    return x.filter(x > x.mean()).count()

def count_above_mean_rewrite(x:pl.Expr) -> pl.Expr:

    return (x > x.mean()).sum()
```

The current implementation is good, but is somewhat wordy and not precise. 

Performance-wise, the two implementation are really close when input column has <200k rows by my testing. Rewrite is about 10-20% faster depending on length on these relatively small data sizes. However, on really long series, say 1mm rows, the rewrite is significantly faster. I think this is because "filter" is essentially a redundant operation, which hints at roughly half of the runtime on larger dataset).

Here are some simple tests:
![image](https://github.com/neocortexdb/functime/assets/72534736/1aea223d-3ad6-4757-af6f-fb165e8a09f0)

![image](https://github.com/neocortexdb/functime/assets/72534736/382e86e4-e0ac-4178-a0fb-82273c5c8362)

**Comment by topher-lo** [comment]
@abstractqqq this makes sense. Go for it.
