### ISSUE TITLE
Bug: change_quantile is lacking an aggregation

### ISSUE THREAD

**Issue by abstractqqq** [neocortexdb/functime#47]
https://tsfresh.readthedocs.io/en/latest/api/tsfresh.feature_extraction.html#tsfresh.feature_extraction.feature_calculators.quantile

The change_quantile function should not return a series. Instead, after all the filtering, we should aggregate over the remaining values in the diff and return the aggregated value. I am proposing to add a type_alias module to add an AggStrategy type. See the issue here: https://github.com/neocortexdb/functime/issues/46

To add the aggregation, we simply need to do: 
```python
# I am proposing a new type_alias module which should contain AggStrategy
from typing_extensions import TypeAlias, Literal
AggStrategy: TypeAlias = Literal["mean", "sum", "median", "std", "max"]
def change_quantile_rewrite(
    x: pl.Expr, 
    q_low: float, 
    q_high: float, 
    is_abs: bool=True, 
    agg: AggStrategy = "mean",
    # Polars' default is nearest, but NumPy's default is linear
    # interpolation: InterpolationMethod = "linear"
) -> pl.Expr:
    
    if q_high <= q_low:
        return pl.lit(0.)

    # Use linear to conform to NumPy
    y = x.is_between(x.quantile(q_low, interpolation="linear"), x.quantile(q_high, interpolation="linear"))
    expr = x.filter(
        pl.all_horizontal(
            y
            , y.shift_and_fill(False, period=-1)
        )
    ).diff() 
    
    if is_abs:
        expr = expr.abs()

    if agg == "mean":
        return expr.mean()
    elif agg == "median":
        return expr.median()
    elif agg == "sum":
        return expr.sum()
    elif agg == "std":
        return expr.std()
    elif agg == "max":
        return expr.max()
    else:
        raise TypeError(f"The input: `{agg}` is not a valid aggregation strategy.")
```

**Comment by topher-lo** [comment]
I suggest we return a list. Let the user decide how to aggregate using pl.Expr.list.explode().mean() for example. This keeps it more flexible than hard coding the aggregation.

**Comment by abstractqqq** [comment]
> I suggest we return a list. Let the user decide how to aggregate using pl.Expr.list.explode().mean() for example. This keeps it more flexible than hard coding the aggregation.

oh I might have missed the discussion on this. We can certainly do that.

**Comment by topher-lo** [comment]
> > I suggest we return a list. Let the user decide how to aggregate using pl.Expr.list.explode().mean() for example. This keeps it more flexible than hard coding the aggregation.
> 
> oh I might have missed the discussion on this. We can certainly do that.

It's point number two in the challenges checklist: https://github.com/neocortexdb/functime/issues/27#issue-1878872087. I could have made it clearer :P

**Comment by topher-lo** [comment]
@abstractqqq can we close this issue?
