### ISSUE TITLE
Import functime.forecasting (zarr) leads to error

### ISSUE THREAD

**Issue by leonhergert** [neocortexdb/functime#51]
with Macbook M1 and zarr-2.16.1 I get the following error

`ImportError: dlopen(/opt/homebrew/lib/python3.10/site-packages/numcodecs/_shuffle.cpython-310-darwin.so, 0x0002): tried: '/opt/homebrew/lib/python3.10/site-packages/numcodecs/_shuffle.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/python3.10/site-packages/numcodecs/_shuffle.cpython-310-darwin.so' (no such file), '/opt/homebrew/lib/python3.10/site-packages/numcodecs/_shuffle.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))`'

**Comment by topher-lo** [comment]
This might be unrelated to `functime`...found this on StackOverflow: https://stackoverflow.com/questions/72920577/mach-o-file-but-is-an-incompatible-architecture-have-arm64-need-x86-64

**Comment by leonhergert** [comment]
fixed it, a lot of pingpong with my os
