### ISSUE TITLE
Possible Name Changes to Some Features 

### ISSUE THREAD

**Issue by abstractqqq** [neocortexdb/functime#53]
I am not sure how Tsfresh decided on some of the names.

E.g. variation_coefficient, but in fact it is [coefficient of variation](https://en.wikipedia.org/wiki/Coefficient_of_variation), in industry we call this CV. I think coefficient_of_variation would be better.

Here is a list of name changes I am proposing, with reasons:
1. variation_coefficient ---> coefficient_of_variation (stated above)
2. absolute_sum_of_changes ---> sum_abs_changes. (absolute_sum_of_changes make people think it is abs(sum(changes)), instead of the actual value, which is sum(abs(changes))

Personally, I prefer a more concise naming convention. For well known items, we can use abbreviations. 
3. large_standard_deviation ---> large_std

The list is not exhaustive. Please comment if you think some other features deserve a name change, or if you think we should stick to Tsfresh's naming conventions.

**Comment by vienneraphael** [comment]
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Feature Name | Proposed New Name | Reason(s) |
-- | -- | -- |
variation_coefficient | coefficient_of_variation | Sticks to industry name |
absolute_sum_of_changes | sum_abs_changes | Possible misunderstanding |
large_standard_deviation | large_std | more concise |

</body>
</html>

Here is the table of propositions, feel free to edit to add things

**Comment by abstractqqq** [comment]
let's keep this ongoing for a while and gather as much feedback as possible. Fixing the names should be easy

**Comment by topher-lo** [comment]
Closing as part of v0.9.0.
