### ISSUE TITLE
Explore Parallel = True in value_counts

### ISSUE THREAD

**Issue by abstractqqq** [neocortexdb/functime#59]
In the docstring, it is mentioned that in group_by context, value_counts = True will likely not improve perf and might even make it worse.  I have two questions, which I do not have time to test out and nor do I have the domain knowledge.

1. In time series, how often will these features be used in a group_by context? It seems to be very often, but I am not sure.
2. Can someone run a benchmark and see the relatively perf differences for value_counts in both select vs. group_by context with Parallel = True/False? I think this is interesting knowledge and would help us later. 
3. One thing that will be super interesting to know is when will Parallel=True outperform Parallel=False. How big the data has to be? Let's assume we are doing value_count on integer columns for now. The result might differ for string columns.

@topher-lo @MathieuCayssol @

**Comment by MathieuCayssol** [comment]
Sure, I will integrate this in my benchmark framework.

I'll keep you update 👍

**Comment by MathieuCayssol** [comment]
Select context:
![newplot](https://github.com/neocortexdb/functime/assets/49449000/2ecc2123-a097-4683-b08e-9e0e11d3ef76)
![newplot (1)](https://github.com/neocortexdb/functime/assets/49449000/11aa665d-1ddd-47e5-b1ea-e7482245cfc7)

Group_by context:
![newplot (2)](https://github.com/neocortexdb/functime/assets/49449000/afd038ba-b2c4-49e2-88ca-0afdc0074abe)
![newplot (3)](https://github.com/neocortexdb/functime/assets/49449000/d4b45479-7fb5-4a81-89dd-9754bfee6bc2)

**Comment by abstractqqq** [comment]
Interesting. It seems like setting Parallel = True is always worth it in eager mode.

It is more debatable in lazy mode.

Contention is likely an issue in lazy mode because the system only has N number of cores. If you are running other tasks in the meantime, the more tasks you launch by setting Parallel = True in value_counts, the more threads has to wait. Would be interesting to see results when value_counts is used with other expressions (2, 3 +) in lazy mode.

**Comment by abstractqqq** [comment]
likely will not enforce Parallel in any case. We can likely talk about this in the future.
