### ISSUE TITLE
Support NumPy 1d Array Whenever Series is Supported

### ISSUE THREAD

**Issue by abstractqqq** [neocortexdb/functime#62]
I think for general purpose computing, we still need to support NumPy 1d array inputs. Asking the user to do Series -> NumPy or NumPy -> Series conversion can be cumbersome.

Most code for Series will work the same for NumPy. More code will need to have clear branches like 

isinstance(x, pl.Series, np.ndarray)

because x.len() won't work on NumPy. But that is just a quick fix, and generally speaking code duplication is not a big deal. 

What do you guys think?

**Comment by topher-lo** [comment]
Could you elaborate with a Coe example? I don't quite understand how your suggestion looks like re: the user facing API

**Comment by abstractqqq** [comment]
> Could you elaborate with a Coe example? I don't quite understand how your suggestion looks like re: the user facing API

No change with regard to user API. We can potentially add np.ndarray to TIME_SERIES_T, or maybe we don't add it but mention that most functions work on NumPy as well, but also mention that if you insist on using NumPy you will miss out on all the benefits provided by Polars or something.. Not sure.. It's an idea to make the package more friendly to people who have backwards compatibility issues, and lots of our optimizations, like the eager version of many entropies, work perfectly fine with NumPy and will be fast.

**Comment by topher-lo** [comment]
Can you run polars functions on numpy arrays? Just double confirming that you suggesting we do a dtype check and data container coersion? Nothing wrong with that imo.

**Comment by baggiponte** [comment]
Could you make an example where this could come up with our use-case? When the input of something is going to be a numpy array? My understanding is that our public interface and intended use is:

```python
from functime.forecasting import linear_model
from functime.preprocessing import scale
from functime.feature_extraction import add_fourier_terms

forecaster = linear_model(
    freq="1mo",
    lags=12,
    target_transform=scale(),
    feature_transform=add_fourier_terms(sp=12, K=3)
)
```

where all interfaces expect a panel dataframe (i.e. 3 columns).

**Comment by topher-lo** [comment]
We are going full polars. If you are using numpy, please convert to polars series first.
