### ISSUE TITLE
`autocorrelation` doesn't return the same result for pl.LazyFrame and pl.DataFrame

### ISSUE THREAD

**Issue by MathieuCayssol** [neocortexdb/functime#65]
The correct result is for the Eager mode.

![Capture d’écran 2023-10-08 à 11 47 02](https://github.com/neocortexdb/functime/assets/49449000/fc049ad3-15c0-424d-a53c-11b8b21eec53)

![Capture d’écran 2023-10-08 à 11 47 54](https://github.com/neocortexdb/functime/assets/49449000/c23ed1d6-a939-4ab4-8418-3fdd0f53a8ce)

**Comment by abstractqqq** [comment]
This is likely a Polars Bug

**Comment by abstractqqq** [comment]
@topher-lo @MathieuCayssol  As of 0.19.8, the underlying Polars issue is fixed. We can try again using slice... Polars updates very fast..... I will implement the change in Mathieu's PR... Let's consider upgrading Polars version? 

See here.
https://github.com/pola-rs/polars/issues/11594

**Comment by MathieuCayssol** [comment]
Thanks a lot @abstractqqq!!! I just updated my PR with your previous implementation and the tests

**Comment by topher-lo** [comment]
Resolved by #66
