### ISSUE TITLE
[FEAT] adding a `num_series` parameter to `plotting.plot_panel` 

### ISSUE THREAD

**Issue by baggiponte** [neocortexdb/functime#75]
Currently, `plot_panel` draws a plot for every ID in the panel. The docs recommend:

> Note: if you have over 10 entities / time-series, we recommend using the rank_ functions in functime.evaluation then df.head() before plotting.

1. I would perhaps provide an example of this
2. Ideally, though, I would like for `plot_panel` to have a `num_series` param to select the number of series to plot. It could either accept an integer (e.g. plot up to k series) a list of integers (plot the series 1, 3, 4...) or a list of strings with the names of the IDs.

**Comment by topher-lo** [comment]
Yes. I would also suggest a n_series argument and also a randomize flag. I agree that most users might be tripped up and forget to use rank to filter.

**Comment by baggiponte** [comment]
On it! 🔥

**Comment by baggiponte** [comment]
Working on a draft, I reckon we could also have an argument "rank" that accepts a valid ranking that we could use to display the series.

**Comment by topher-lo** [comment]
Resolved.
