### ISSUE TITLE
Fractional Differentiation

### ISSUE THREAD

**Issue by ngriffiths13** [neocortexdb/functime#97]
Would there be any interest in adding fraction differencing as a function to the library? This is talked about in [M. L. Prado, "Advances in Financial Machine Learning"](https://www.wiley.com/en-us/Advances+in+Financial+Machine+Learning-p-9781119482086). I have an implementation already in polars I could clean up and make a PR for if there is any interest.

You can also see [this repo](https://github.com/fracdiff/fracdiff) for a numpy example

**Comment by topher-lo** [comment]
Absolutely. Big fan of this technique. Would you have a recipe for the inverse operation?

**Comment by ngriffiths13** [comment]
I don't believe you can calculate the inverse because it requires a dot product.

**Comment by abstractqqq** [comment]
@ngriffiths13 Is your implementation pure Polars expressions? Or it requires NumPy/SciPy under the hood?

**Comment by ngriffiths13** [comment]
@abstractqqq i use numpy to calculate the weights before doing anything to the frame. But everything that happens to the frame is pure polars. Could remove numpy completely pretty easily if needed.

**Comment by ngriffiths13** [comment]
@topher-lo I actually have been implementing most of the functions in the book referenced above. If any other ones interest you I would be happy to contribute more of them. (If you aren't familiar with the book I can put together a list)

**Comment by topher-lo** [comment]
Let's do it. I'm super excited to see this in action.

**Comment by topher-lo** [comment]
If you haven't already, please join our discord! We can then add you to the (very active) private contributors channel and take it from there.
